# https://mail.haskell.org/pipermail/ghc-devs/2017-July/014364.html
# https://downloads.haskell.org/~ghc/8.2.1-rc3/
# http://taylor.fausak.me/2017/05/17/testing-ghc-release-candidates-with-stack/
compiler: ghc-8.2.0.20170704
compiler-check: match-exact

resolver: ghc-8.2.0.20170704

setup-info:
  ghc:

    linux64:
      8.2.0.20170704:
        url: https://downloads.haskell.org/~ghc/8.2.1-rc3/ghc-8.2.0.20170704-x86_64-deb8-linux.tar.xz
        content-length: 138482820
        sha1: ac1598c21ea2936b091885a29a0f5725668aaed5
